[metadata]
name = "sl-show"
description = "A channel to select files from the current commit"
requirements = ["sl"]

[source]
command = "sl status --change . --no-status"

[preview]
command = "sl diff -c . --color=always -- '{}'"

[keybindings]
ctrl-e = "actions:edit"

[actions.edit]
description = "Edit selected file"
command = "${EDITOR:-vim} '{}'"
mode = "execute"
